version: '3'
services:
#  db:
#    image: postgres
  web:
    build: .
    volumes:
    - .:/app
    links:
    - redis
    - elasticsearch
    command: python manage.py runserver 0.0.0.0:5000
    ports:
    - "5000:5000"
    - "8080:8080"
#    depends_on:
#      - db
  redis:
    image: redis
  worker:
    build: .
    volumes:
    - .:/app
    links:
    - redis
    command: python manage.py rqworker default
#    depends_on:
#      - db
  elasticsearch:
    image: blacktop/elasticsearch:7.6
#    ports:
#      - "9200:9200"
volumes:
  logvolume01: {}