# Generated by Django 3.0.5 on 2020-04-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_notif'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notif',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following_user_id',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user_id',
            new_name='following',
        ),
    ]
